spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 2
      filter: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        log-slow-sql: true
        exclusions: "*.js,*jpg,*.png,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /durid/*
        login-username: aaa
        login-password: bbb
        allow: 127.0.0.1
        deny: ""
        reset-enable: true
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.3.135.10:3316/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.3.135.10:3317/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=ASia/Shanghai
          username: root
          password: root

mybatis:
  type-aliases-package: com.song.collect.domain.entity
  mapper-locations: classpath:mappers/**/*.xml
